import { TmLayer } from '@/types/taskm';

export const LAYER_DEFINITIONS = [
   { index: 0, name: 'Discovery', description: 'Project spec, goals, sitemap, constraints' },
   {
      index: 1,
      name: 'UX & Flows',
      description: 'Page flows, conversion architecture, popup specs',
   },
   { index: 2, name: 'Backend', description: 'Auth, DB schema, API contracts, integrations' },
   { index: 3, name: 'Components', description: 'Component inventory, page assignments' },
   { index: 4, name: 'Design', description: 'Design tokens, UX micro-patterns, visual grammar' },
   { index: 5, name: 'Copy', description: 'Content strategy, microcopy, page content' },
   { index: 6, name: 'QA', description: 'Coherence check, visual QA, test results' },
] as const;

export const tmLayers: TmLayer[] = [
   {
      id: 'ghobz-realtor-l0',
      projectId: 'ghobz-realtor',
      index: 0,
      name: 'Discovery',
      description: 'Project spec, goals, sitemap, constraints',
      state: 'complete',
      percentComplete: 100,
   },
   {
      id: 'ghobz-realtor-l1',
      projectId: 'ghobz-realtor',
      index: 1,
      name: 'UX & Flows',
      description: 'Page flows, conversion architecture, popup specs',
      state: 'complete',
      percentComplete: 100,
   },
   {
      id: 'ghobz-realtor-l2',
      projectId: 'ghobz-realtor',
      index: 2,
      name: 'Backend',
      description: 'Auth, DB schema, API contracts, integrations',
      state: 'in-progress',
      percentComplete: 60,
   },
   {
      id: 'ghobz-realtor-l3',
      projectId: 'ghobz-realtor',
      index: 3,
      name: 'Components',
      description: 'Component inventory, page assignments',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'ghobz-realtor-l4',
      projectId: 'ghobz-realtor',
      index: 4,
      name: 'Design',
      description: 'Design tokens, UX micro-patterns, visual grammar',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'ghobz-realtor-l5',
      projectId: 'ghobz-realtor',
      index: 5,
      name: 'Copy',
      description: 'Content strategy, microcopy, page content',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'ghobz-realtor-l6',
      projectId: 'ghobz-realtor',
      index: 6,
      name: 'QA',
      description: 'Coherence check, visual QA, test results',
      state: 'not-started',
      percentComplete: 0,
   },
   // taskm-core layers
   {
      id: 'taskm-core-l0',
      projectId: 'taskm-core',
      index: 0,
      name: 'Discovery',
      description: 'Project spec, goals, sitemap, constraints',
      state: 'complete',
      percentComplete: 100,
   },
   {
      id: 'taskm-core-l1',
      projectId: 'taskm-core',
      index: 1,
      name: 'UX & Flows',
      description: 'Page flows, conversion architecture, popup specs',
      state: 'in-progress',
      percentComplete: 40,
   },
   {
      id: 'taskm-core-l2',
      projectId: 'taskm-core',
      index: 2,
      name: 'Backend',
      description: 'Auth, DB schema, API contracts, integrations',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'taskm-core-l3',
      projectId: 'taskm-core',
      index: 3,
      name: 'Components',
      description: 'Component inventory, page assignments',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'taskm-core-l4',
      projectId: 'taskm-core',
      index: 4,
      name: 'Design',
      description: 'Design tokens, UX micro-patterns, visual grammar',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'taskm-core-l5',
      projectId: 'taskm-core',
      index: 5,
      name: 'Copy',
      description: 'Content strategy, microcopy, page content',
      state: 'not-started',
      percentComplete: 0,
   },
   {
      id: 'taskm-core-l6',
      projectId: 'taskm-core',
      index: 6,
      name: 'QA',
      description: 'Coherence check, visual QA, test results',
      state: 'not-started',
      percentComplete: 0,
   },
];
